gcfg: first GCFG ILP

diff --git a/ext/detect_ruby_commands b/ext/detect_ruby_commands
--- a/ext/detect_ruby_commands
+++ b/ext/detect_ruby_commands
@@ -31,8 +31,9 @@ detect_ruby() {
     if [ -z "${RUBY}" ] ; then
 	echo "ruby not found. Please install ruby (e.g., sudo aptitude install ruby1.9.1)" >&2
 	exit 1
-    elif [ -z "${RUBY19}" ] ; then
-	echo "ruby1.9 not found. Falling back to unsupported ruby version `${RUBY} -v`" >&2
+    #elif [ -z "${RUBY19}" ] ; then
+
+	# echo "ruby1.9 not found. Falling back to unsupported ruby version `${RUBY} -v`" >&2
     fi
 }
 
